import TanstackProvider from "@/providers/TanstackProvider";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next | Tanstack | Antd",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <TanstackProvider>
          <AntdRegistry>{children}</AntdRegistry>
        </TanstackProvider>
      </body>
    </html>
  );
}
